array: []
version: 3.2.1
woopra_config:
  domain: "ssvp.fr"
  cookie_domain: ".ssvp.fr"
form-to-db_config:
  schema: "ssvp"
  envoi_base_de_donnée: true
  message_erreur: "Une erreur est survenue, veuillez envoyer un mail à lghionna@adfinitas.fr"
controles:
  - telephone
types:
  - champ_libre_court
  - champ_libre_long
  - liste_deroulante
  - choix_unique
  - choix_multiple
  - scoring
largeur_champs:
  - "100%"
  - "50% centré"
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: formulaire
    values:
      layout: formulaire
  - scope:
      path: ''
      type: petition
    values:
      layout: petition
collections:
  formulaire:
    output: true
    permalink: /:collection/:title/
    _hide_content: true
